'use client';

/**
 * Drop-in panel for showing + regenerating a Lead's signal icebreaker.
 *
 * Backend pair:
 *   GET  /api/linkedin/leads/:id/icebreaker
 *   POST /api/linkedin/leads/:id/icebreaker/regenerate
 *
 * The icebreaker is auto-generated by supervisor.ts on signal promotion.
 * This panel surfaces (a) the stored text — so an operator can preview
 * what will land at {{signal_icebreaker}} — and (b) a regenerate button
 * for when the operator wants to re-run after editing prompt config or
 * after the poller captured better post text on a later cycle.
 */

import { useCallback, useEffect, useState } from 'react';
import { Sparkles, RotateCw, Loader2, AlertCircle } from 'lucide-react';
import { apiClient } from '@/lib/api';
import toast from 'react-hot-toast';

interface IcebreakerData {
    id: string;
    full_name: string | null;
    signal_icebreaker: string | null;
    signal_icebreaker_generated_at: string | null;
    signal_icebreaker_event_id: string | null;
    signal_icebreaker_skip_reason: string | null;
}

interface Props {
    leadId: string;
    /** Optional compact mode for narrow drawers. */
    compact?: boolean;
}

const SKIP_REASON_COPY: Record<string, string> = {
    openai_not_configured: 'OpenAI API key not configured for this workspace.',
    event_not_found: 'No engagement event to reference.',
    no_grounding_context: 'Post body and comment text are both empty — generator has nothing to ground on.',
    unknown: 'Skipped — see worker logs.',
};

export default function IcebreakerPanel({ leadId, compact }: Props) {
    const [data, setData] = useState<IcebreakerData | null>(null);
    const [loading, setLoading] = useState(true);
    const [regenerating, setRegenerating] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const fetchData = useCallback(async () => {
        setLoading(true);
        setError(null);
        try {
            const resp = await apiClient<{ data: IcebreakerData } | IcebreakerData>(
                `/api/linkedin/leads/${leadId}/icebreaker`,
            );
            const row = (resp as any)?.data ?? resp;
            setData(row);
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Failed to load icebreaker');
        } finally {
            setLoading(false);
        }
    }, [leadId]);

    useEffect(() => { fetchData(); }, [fetchData]);

    const regenerate = async () => {
        setRegenerating(true);
        try {
            const resp = await apiClient<{ success: boolean; skipped?: boolean; skip_reason?: string; data?: IcebreakerData }>(
                `/api/linkedin/leads/${leadId}/icebreaker/regenerate`,
                { method: 'POST' },
            );
            if (resp.skipped) {
                const reason = resp.skip_reason || 'unknown';
                toast.error(SKIP_REASON_COPY[reason] || `Skipped (${reason.replace(/_/g, ' ')})`);
            } else {
                toast.success('Icebreaker regenerated');
                await fetchData();
            }
        } catch (err: any) {
            toast.error(err?.message || 'Regenerate failed');
        } finally {
            setRegenerating(false);
        }
    };

    if (loading) {
        return (
            <div className="flex items-center gap-2 text-xs text-gray-500 py-2">
                <Loader2 size={12} className="animate-spin" /> Loading icebreaker…
            </div>
        );
    }

    if (error) {
        return (
            <div className="flex items-start gap-2 text-xs text-rose-700 bg-rose-50 border border-rose-200 rounded-md px-2.5 py-2">
                <AlertCircle size={12} className="mt-0.5 shrink-0" />
                <div>{error}</div>
            </div>
        );
    }

    const text = data?.signal_icebreaker ?? null;
    const generatedAt = data?.signal_icebreaker_generated_at ?? null;

    return (
        <div className={`border border-violet-200 bg-violet-50/40 rounded-md ${compact ? 'p-2.5' : 'p-3'}`}>
            <div className="flex items-center justify-between mb-1.5">
                <div className="flex items-center gap-1.5 text-[0.7rem] font-bold text-violet-900 uppercase tracking-wide">
                    <Sparkles size={12} /> Signal icebreaker
                </div>
                <button
                    onClick={regenerate}
                    disabled={regenerating}
                    className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[0.65rem] font-semibold text-violet-700 hover:bg-violet-100 disabled:opacity-50"
                >
                    {regenerating ? <Loader2 size={10} className="animate-spin" /> : <RotateCw size={10} />}
                    {regenerating ? 'Generating…' : 'Regenerate'}
                </button>
            </div>
            {text ? (
                <>
                    <p className={`text-gray-900 leading-snug ${compact ? 'text-[0.75rem]' : 'text-xs'}`}>
                        &ldquo;{text}&rdquo;
                    </p>
                    {generatedAt && (
                        <p className="text-[0.6rem] text-violet-700/70 mt-1">
                            Generated {new Date(generatedAt).toLocaleString()}
                        </p>
                    )}
                </>
            ) : data?.signal_icebreaker_skip_reason ? (
                // Last attempt skipped — explain why so the operator can
                // either fix the underlying issue (e.g. add OpenAI key)
                // or write the opener manually.
                <div className="text-[0.7rem] text-violet-800">
                    <div className="font-semibold mb-0.5">Auto-generation skipped:</div>
                    <div className="text-violet-700">
                        {SKIP_REASON_COPY[data.signal_icebreaker_skip_reason] ||
                            `Reason: ${data.signal_icebreaker_skip_reason.replace(/_/g, ' ')}.`}
                    </div>
                    <div className="text-violet-600 mt-1">Click regenerate to retry, or paste a manual opener below.</div>
                </div>
            ) : (
                <p className="text-[0.7rem] text-violet-700 italic">
                    No icebreaker generated yet. Click regenerate to seed one from the lead&apos;s most recent engagement event.
                </p>
            )}
            <p className="text-[0.6rem] text-violet-700/60 mt-2">
                Renders as <code className="bg-violet-100 px-1 rounded">{`{{signal_icebreaker}}`}</code> in sequence steps.
            </p>
        </div>
    );
}
