import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Load Balancing Suggestions Explained | Superkabe Help',
    description: 'Learn how Superkabe analyzes your mailbox distribution and generates specific recommendations to improve deliverability through load rebalancing.',
    alternates: { canonical: '/docs/help/optimization-suggestions' },
    openGraph: {
        title: 'Load Balancing Suggestions Explained | Superkabe Help',
        description: 'Learn how Superkabe analyzes your mailbox distribution and generates specific recommendations to improve deliverability through load rebalancing.',
        url: '/docs/help/optimization-suggestions',
        siteName: 'Superkabe',
        type: 'article',
    },
};

export default function OptimizationSuggestionsPage() {
    return (
        <div className="prose prose-lg text-gray-700 max-w-none">
            <h1 className="text-5xl font-bold mb-6 text-gray-900">
                Load Balancing Suggestions Explained
            </h1>
            <p className="text-xl text-gray-500 mb-12">
                How Superkabe identifies imbalances and recommends specific actions to protect deliverability
            </p>

            {/* Quick Answer */}
            <div className="bg-blue-50 border-l-4 border-blue-500 p-6 mb-12 rounded-r-lg">
                <h2 className="text-xl font-bold mb-3 text-blue-900">Quick Answer</h2>
                <p className="text-blue-800">
                    Superkabe analyzes your mailbox distribution and generates specific recommendations to improve deliverability
                    by rebalancing load. Each suggestion tells you <strong>what</strong> to change, <strong>why</strong> it matters,
                    and <strong>how</strong> to implement it.
                </p>
            </div>

            {/* What the Page Shows */}
            <h2 className="text-3xl font-bold mb-6 text-gray-900">What the Optimization Suggestions Page Shows</h2>
            <div className="bg-gradient-to-br from-blue-50 to-purple-50 border-2 border-blue-200 rounded-2xl p-8 mb-12">
                <p className="text-gray-700 mb-4">
                    The suggestions page is a prioritized list of actionable recommendations. Each suggestion is generated by analyzing your
                    current mailbox-to-campaign assignments, domain distribution, and sending volumes.
                </p>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                    <div className="bg-white rounded-xl p-4 border border-blue-200">
                        <h3 className="font-bold text-gray-900 mb-2">Priority Level</h3>
                        <p className="text-gray-600">Each suggestion is ranked by impact. High-priority items affect deliverability immediately; low-priority items are optimizations.</p>
                    </div>
                    <div className="bg-white rounded-xl p-4 border border-blue-200">
                        <h3 className="font-bold text-gray-900 mb-2">Affected Entities</h3>
                        <p className="text-gray-600">Shows the specific mailboxes, campaigns, or domains involved so you know exactly what to act on.</p>
                    </div>
                    <div className="bg-white rounded-xl p-4 border border-blue-200">
                        <h3 className="font-bold text-gray-900 mb-2">Reasoning</h3>
                        <p className="text-gray-600">Every suggestion includes a clear explanation of the problem and the expected improvement from acting on it.</p>
                    </div>
                </div>
            </div>

            {/* Types of Suggestions */}
            <h2 className="text-3xl font-bold mb-8 text-gray-900">Types of Suggestions</h2>

            {/* Type 1: Add Mailboxes */}
            <div className="bg-white border-l-4 border-amber-500 rounded-r-2xl p-6 shadow-lg mb-6">
                <div className="flex items-start gap-4">
                    <div className="flex-shrink-0 w-12 h-12 bg-amber-100 rounded-full flex items-center justify-center font-bold text-amber-700 text-lg">
                        +
                    </div>
                    <div className="flex-1">
                        <h3 className="text-xl font-bold text-gray-900 mb-3">Add Mailboxes to Underloaded Campaigns</h3>
                        <div className="space-y-3">
                            <div className="bg-amber-50 rounded-lg p-4 border border-amber-100">
                                <p className="text-sm text-gray-700"><strong>What:</strong> A campaign has fewer mailboxes than recommended, putting excessive load on each one.</p>
                            </div>
                            <div className="bg-amber-50 rounded-lg p-4 border border-amber-100">
                                <p className="text-sm text-gray-700"><strong>Why:</strong> When too few mailboxes handle a campaign, each mailbox sends more emails. This increases per-mailbox volume, which raises the risk of hitting ESP rate limits and damaging sender reputation.</p>
                            </div>
                            <div className="bg-amber-50 rounded-lg p-4 border border-amber-100">
                                <p className="text-sm text-gray-700"><strong>How:</strong> Assign additional healthy mailboxes from the same domain (or new domains) to the campaign. The suggestion will list specific mailboxes that are available and have capacity.</p>
                            </div>
                        </div>
                        <div className="mt-4 bg-white rounded-lg p-4 border border-gray-200">
                            <p className="text-xs text-gray-600"><strong>Example:</strong> &ldquo;Campaign &lsquo;Enterprise Outreach Q1&rsquo; has only 1 mailbox assigned. Add 2&ndash;3 more mailboxes to reduce per-mailbox volume from ~150/day to ~40/day.&rdquo;</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Type 2: Remove Mailboxes */}
            <div className="bg-white border-l-4 border-red-500 rounded-r-2xl p-6 shadow-lg mb-6">
                <div className="flex items-start gap-4">
                    <div className="flex-shrink-0 w-12 h-12 bg-red-100 rounded-full flex items-center justify-center font-bold text-red-700 text-lg">
                        &minus;
                    </div>
                    <div className="flex-1">
                        <h3 className="text-xl font-bold text-gray-900 mb-3">Remove Mailboxes from Overloaded Campaigns</h3>
                        <div className="space-y-3">
                            <div className="bg-red-50 rounded-lg p-4 border border-red-100">
                                <p className="text-sm text-gray-700"><strong>What:</strong> A mailbox is assigned to too many campaigns simultaneously, spreading it thin and increasing total daily volume.</p>
                            </div>
                            <div className="bg-red-50 rounded-lg p-4 border border-red-100">
                                <p className="text-sm text-gray-700"><strong>Why:</strong> A single mailbox in 8 campaigns will send far more emails per day than one in 2 campaigns. Overloaded mailboxes are more likely to trigger spam filters and accumulate bounces faster.</p>
                            </div>
                            <div className="bg-red-50 rounded-lg p-4 border border-red-100">
                                <p className="text-sm text-gray-700"><strong>How:</strong> Remove the mailbox from lower-priority campaigns, or redistribute campaigns across more mailboxes. The suggestion identifies which campaigns to remove it from.</p>
                            </div>
                        </div>
                        <div className="mt-4 bg-white rounded-lg p-4 border border-gray-200">
                            <p className="text-xs text-gray-600"><strong>Example:</strong> &ldquo;john@acmecorp.com is in 7 campaigns. Remove from 3 lowest-volume campaigns to bring effective load from 210 emails/day to ~80 emails/day.&rdquo;</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Type 3: Redistribute */}
            <div className="bg-white border-l-4 border-blue-500 rounded-r-2xl p-6 shadow-lg mb-12">
                <div className="flex items-start gap-4">
                    <div className="flex-shrink-0 w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center font-bold text-blue-700 text-lg">
                        &#x21C4;
                    </div>
                    <div className="flex-1">
                        <h3 className="text-xl font-bold text-gray-900 mb-3">Redistribute Across Domains</h3>
                        <div className="space-y-3">
                            <div className="bg-blue-50 rounded-lg p-4 border border-blue-100">
                                <p className="text-sm text-gray-700"><strong>What:</strong> A campaign relies heavily on a single domain. If that domain gets blacklisted or flagged, the entire campaign stops.</p>
                            </div>
                            <div className="bg-blue-50 rounded-lg p-4 border border-blue-100">
                                <p className="text-sm text-gray-700"><strong>Why:</strong> Domain diversity is critical. If 100% of a campaign&rsquo;s mailboxes are on @acmecorp.com and that domain gets blacklisted, the campaign has zero fallback. Spreading across 2&ndash;3 domains provides resilience.</p>
                            </div>
                            <div className="bg-blue-50 rounded-lg p-4 border border-blue-100">
                                <p className="text-sm text-gray-700"><strong>How:</strong> Add mailboxes from different domains to the campaign. The suggestion identifies which domains are over-concentrated and which have available capacity.</p>
                            </div>
                        </div>
                        <div className="mt-4 bg-white rounded-lg p-4 border border-gray-200">
                            <p className="text-xs text-gray-600"><strong>Example:</strong> &ldquo;Campaign &lsquo;SMB Outbound&rsquo; uses 4 mailboxes, all on acmecorp.com. Add 1&ndash;2 mailboxes from altdomain.com to reduce single-domain dependency.&rdquo;</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* How Effective Load Is Calculated */}
            <h2 className="text-3xl font-bold mb-6 text-gray-900">How Effective Load Is Calculated</h2>
            <div className="bg-white border-2 border-gray-200 rounded-2xl p-8 mb-12 shadow-sm">
                <p className="text-gray-700 mb-4">
                    Effective load is not simply &ldquo;how many campaigns is this mailbox in.&rdquo; It accounts for the <strong>weight</strong> of each campaign
                    based on how many other mailboxes share the work.
                </p>
                <div className="bg-gray-50 rounded-xl p-6 mb-6 text-center">
                    <p className="text-lg font-mono text-gray-800 mb-2">
                        <strong>Effective Load</strong> = &sum; (1 &divide; mailboxes_in_campaign) for each campaign
                    </p>
                    <p className="text-sm text-gray-500">A mailbox that is the sole sender in a campaign has load = 1.0 for that campaign. A mailbox sharing with 3 others has load = 0.25.</p>
                </div>

                <div className="space-y-4">
                    <div className="bg-white rounded-lg p-4 border border-gray-200">
                        <h3 className="font-bold text-gray-900 mb-2">Example: Same Campaign Count, Different Load</h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-gray-700">
                            <div className="bg-red-50 rounded-lg p-4">
                                <p className="font-bold mb-1">Mailbox A: 3 campaigns</p>
                                <p>Campaign 1 (1 mailbox): load = 1.0</p>
                                <p>Campaign 2 (1 mailbox): load = 1.0</p>
                                <p>Campaign 3 (2 mailboxes): load = 0.5</p>
                                <p className="font-bold mt-2">Total effective load: 2.5</p>
                            </div>
                            <div className="bg-green-50 rounded-lg p-4">
                                <p className="font-bold mb-1">Mailbox B: 3 campaigns</p>
                                <p>Campaign 1 (4 mailboxes): load = 0.25</p>
                                <p>Campaign 2 (5 mailboxes): load = 0.20</p>
                                <p>Campaign 3 (3 mailboxes): load = 0.33</p>
                                <p className="font-bold mt-2">Total effective load: 0.78</p>
                            </div>
                        </div>
                        <p className="text-xs text-gray-500 mt-3">Both mailboxes are in 3 campaigns, but Mailbox A carries 3x more effective load because it&rsquo;s the sole sender in 2 of them.</p>
                    </div>
                </div>
            </div>

            {/* Tips */}
            <div className="bg-green-50 border-l-4 border-green-500 p-6 mb-12 rounded-r-lg">
                <h2 className="text-xl font-bold mb-3 text-green-900">Tips for Acting on Suggestions</h2>
                <ul className="space-y-3 text-sm text-green-800">
                    <li>&#x2022; <strong>Start with high-priority suggestions.</strong> These have the biggest impact on deliverability and are the most urgent to fix.</li>
                    <li>&#x2022; <strong>Don&rsquo;t over-correct.</strong> You don&rsquo;t need to act on every suggestion immediately. Focus on the top 2&ndash;3 and re-check after implementation.</li>
                    <li>&#x2022; <strong>Suggestions update automatically.</strong> After you rebalance, the system re-analyzes and removes resolved suggestions or generates new ones.</li>
                    <li>&#x2022; <strong>Use the load balancing page alongside this.</strong> The load balancing page shows the current distribution; the suggestions page tells you how to improve it.</li>
                </ul>
            </div>

            {/* Warning */}
            <div className="bg-amber-50 border-l-4 border-amber-500 p-6 mb-12 rounded-r-lg">
                <h2 className="text-xl font-bold mb-3 text-amber-900">When to Ignore Suggestions</h2>
                <p className="text-amber-800 mb-4">
                    Suggestions are recommendations, not requirements. You may want to ignore a suggestion if:
                </p>
                <ul className="space-y-2 text-sm text-amber-800">
                    <li>&#x2022; The campaign is intentionally single-mailbox for testing purposes</li>
                    <li>&#x2022; You&rsquo;re winding down a campaign and don&rsquo;t want to add resources</li>
                    <li>&#x2022; Domain concentration is intentional for brand consistency</li>
                    <li>&#x2022; The suggested mailbox is reserved for a specific upcoming campaign</li>
                </ul>
            </div>

            {/* Related Articles */}
            <div className="bg-blue-50 border border-blue-200 rounded-2xl p-6">
                <h3 className="text-lg font-bold text-gray-900 mb-4">Related Help Articles</h3>
                <div className="space-y-2">
                    <a href="/docs/help/load-balancing" className="block p-3 bg-white rounded-lg hover:bg-blue-50 transition-colors text-blue-600 hover:text-blue-700 text-sm font-medium">
                        &rarr; How Load Balancing Works
                    </a>
                    <a href="/docs/help/mailbox-rotation" className="block p-3 bg-white rounded-lg hover:bg-blue-50 transition-colors text-blue-600 hover:text-blue-700 text-sm font-medium">
                        &rarr; How Does Mailbox Rotation Work?
                    </a>
                    <a href="/docs/help/entity-statuses" className="block p-3 bg-white rounded-lg hover:bg-blue-50 transition-colors text-blue-600 hover:text-blue-700 text-sm font-medium">
                        &rarr; Understanding Status Labels
                    </a>
                    <a href="/docs/help/infrastructure-score-explained" className="block p-3 bg-white rounded-lg hover:bg-blue-50 transition-colors text-blue-600 hover:text-blue-700 text-sm font-medium">
                        &rarr; Understanding Infrastructure Score
                    </a>
                </div>
            </div>
        </div>
    );
}
